refactor code and update readme

diff --git a/inf b/inf
--- a/inf
+++ b/inf
@@ -3,106 +3,147 @@ set -e
 
 usage() {
     printf 'Usage: %s [ARGS] COMPILE_CMD\n' "$(basename "$0")"
-    printf '\t-r | --runcmd  : Execution target command\n'
-    printf '\t-n | --norun   : No run (compile-only)\n'
-    printf '\t-e | --exec    : Target file\n'
+    printf '\t-r | --run     : Target execution command\n'
     printf '\t-i | --input   : Input file\n'
-    printf '\t-z | --noinput : No input\n'
-    printf '\t-f | --file    : Source file\n'
     printf '\t-m | --monitor : Extra comma-separated files to trigger recompilation\n'
+    printf '\t-n | --noparse : Don'"'"'t look for *.* names patterns in compile command\n'
     printf '\t-v | --verbose : Verbose compiler output\n'
+    printf '\t-d | --debug   : Print and validate parsed arguments\n'
     printf '\t-h | --help    : Print this message\n'
 }
 
 compileAndRun() {
-    printf '\033[0;34m[compilation: %s]\033[0m\n' "${compileCmd}"
+    if [[ ${nocompile} != 1 ]]; then
+        printf '\033[1;34m[compilation: %s]\033[0m\n' "${compileCmd}"
+    fi
 
     # In case of executing compile target
     # suppress stdout of compile command
     # if not requested `verbose` for cleanliness
-    if [[ ${norun} = 0 ]]; then
-        if [[ ${verbose} = 1 ]]; then
-            eval "${compileCmd}"
-        else
-            eval "${compileCmd}" 1>/dev/null
+    if [[ ${norun} != 1 ]]; then
+        if [[ ${nocompile} != 1 ]]; then
+            if [[ ${verbose} = 1 ]]; then
+                eval "${compileCmd}"
+            else
+                eval "${compileCmd}" 1>/dev/null
+            fi
+            compileCode=$?
         fi
-        compileCode=$?
-        if [[ ${compileCode} = 0 ]]; then
-            printf '\033[0;32m%s\033[0m\n' "${runCmd}"
+        if [[ ${nocompile} == 1 || ${compileCode} = 0 ]]; then
+            printf '\033[1;32m%s\033[0m\n' "${runCmd}"
             eval "${runCmd}"
         fi
-    else
+    elif [[ ${nocompile} != 1 ]]; then
         eval "${compileCmd}"
+        compileCode=$?
+        if [[ ${compileCode} = 0 ]]; then
+            printf '\033[1;32mCompilation succeeded!\033[0m\n'
+        fi
     fi
 }
 
+add_monitor_files() {
+    IFS=',' read -r -a newFiles <<< "$1"
+    monitorFiles+=("${newFiles[@]}")
+}
+
 parse_args() {
+    monitorFiles=()
     while [[ "$1" != "" ]]; do
         case "$1" in
-                -r | --runcmd    ) export runCmd="$2"       ; shift;;
-                -n | --norun     ) export norun=1                  ;;
-                -e | --exec      ) export exec="$2"         ; shift;;
-                -i | --input     ) export inputfile="$3"    ; shift;;
-                -z | --zeroinput ) export noinput=1                ;;
-                -f | --file      ) export filename="$2"     ; shift;;
-                -m | --monitor   ) export monitorFiles="$2" ; shift;;
-                -v | --verbose   ) export verbose=1                ;;
-                -h | --help      ) usage                    ;  exit;;
-                * ) break;;
+                -r | --run       ) runCmd="$2"            ; shift;;
+                -i | --input     ) inputfile="$2"         ; shift;;
+                -m | --monitor   ) add_monitor_files "$2" ; shift;;
+                -v | --verbose   ) verbose=1                     ;;
+                -d | --debug     ) debug=1                       ;;
+                -h | --help      ) usage                  ;  exit;;
+                 - | --          )                   shift; break;;
+                 *               )                          break;;
         esac
         shift
     done
 
-    # If filename isn't passed explicitly,
-    # try to take the last argument
-    # and match for pattern *.*
-    if [[ -z ${filename+x} ]]; then
-        export filename=${filename:-"${@: -1}"}
-        export implicitFilename=1
-    fi
-    export exec=${exec:-${filename%.*}}
-    export inputfile=${inputfile:-"${exec}.in"}
-    export norun=${norun:-0}
-    export noinput=${noinput:-0}
-    export runCmd="${runCmd:-"./${exec}"}"
-
-    # Pass input file to the execution of compilation target
-    if [[ ${noinput} = 1 ]]; then
-        export inputfile=""
-    else
-        export runCmd="${runCmd} <${inputfile}"
-    fi
-    if [[ ${norun} = 1 ]]; then
-        export inputfile=""
-        export runCmd=""
-    fi
-
-    # Collect all the files, editing of which
-    # will trigger recompilation
-    if [[ -n ${monitorFiles+x} ]]; then
-        IFS=',' read -r -a monitorFiles <<< "${monitorFiles}"
-    else
-        monitorFiles=()
-    fi
-    monitorFiles+=("${filename}")
-    monitorFiles+=("${inputfile}")
-    export monitorFiles
     # Compile command is the rest consisting of non-parsed arguments
-    export compileCmd="$*"
+    compileCmd="$*"
+    if [[ -z ${compileCmd} ]]; then
+        unset compileCmd
+        nocompile=1
+    fi
+    if [[ -z ${inputfile+x} ]]; then
+        noinput=1
+    fi
+    if [[ -z ${runCmd+x} ]]; then
+        norun=1
+    elif [[ ${noinput} != 1 ]]; then
+        runCmd="${runCmd} <${inputfile}"
+    fi
+    if [[ ${noinput} != 1 && ${norun} != 1 ]]; then
+        monitorFiles+=("${inputfile}")
+    fi
+
+    # Search for *.* file names patterns in compile command
+    # and monitor changes in such files
+    if [[ ${nocompile} != 1 ]]; then
+        regex='^[^[:space:]]+\.[^[:space:]]+$'
+        read -ra compileArgs <<<"${compileCmd}"
+        for arg in "${compileArgs[@]:1}"; do
+            if [[ "${arg}" =~ ${regex} && -f "${arg}" ]]; then
+                monitorFiles+=("${arg}")
+            fi
+        done
+    fi
+}
+
+debug_print_args() {
+    if [[ ${debug} != 1 ]]; then
+        return
+    fi
+    args_list=("compileCmd" "runCmd" "inputfile"
+        "nocompile" "norun" "noinput" "verbose" "debug")
+    printf '\033[1;32mParsed arguments:\033[0m\n'
+    for arg in "${args_list[@]}"; do
+        if [[ -n ${!arg+x} ]]; then
+            printf '\033[0;34m%s\033[0m=%s\n' "${arg}" "${!arg}"
+        fi
+    done
+    printf '\033[0;34m%s[*]\033[0m=%s\n' "monitorFiles" "${monitorFiles[*]}"
+}
+
+parse_input() {
+    # If no files are piped into the script
+    # then do nothing
+    # else treat it as a list of files to monitor
+    if [[ -t 0 ]]; then
+        return
+    fi
+    while read -r line; do
+        for file in ${line}; do
+            monitorFiles+=("${file}")
+        done
+    done
 }
 
 error() {
-    errorMessage=$1
-    code=$2
+    code=$1
+    errorMessage=$2
     printf '\033[0;31mERROR: %s\033[0m\n' "${errorMessage}"
     exit "${code}"
 }
 
-validate() {
-    # Fail in case of absence of the compilation command
-    if [[ -z "${compileCmd}" ]]; then
-        usage;
-        exit 1;
+validate_args() {
+    mutual_exclusive=("nocompile,compileCmd" "norun,runCmd" "noinput,inputfile")
+    for args in "${mutual_exclusive[@]}"; do
+        IFS=',' read -r arg1 arg2 <<<"${args}"
+        if [[ -z ${!arg1+x} && -z ${!arg2+x} ]]; then
+            error 2 "$(printf 'None of "%s" or "%s" arguments are passed' "${arg1}" "${arg2}")"
+        fi
+        if [[ -n ${!arg1+x} && -n ${!arg2+x} ]]; then
+            error 2 "$(printf 'Both "%s" and "%s" arguments are passed' "${arg1}" "${arg2}")"
+        fi
+    done
+    # Fail if there is no files to monitor
+    if [[ -z "${monitorFiles[*]}" ]]; then
+        error 3 "no files to monitor"
     fi
     # Fail if some files required for monitoring don't exist
     missingFiles=()
@@ -116,23 +157,32 @@ validate() {
         [[ ${#missingFiles[@]} -gt 1 ]] && pref+="s"
         msg=$(printf 'missing %s ' "${pref}"; \
               printf '"%s" ' "${missingFiles[@]}")
-        error "${msg}" 2
+        error 4 "${msg}"
     fi
-    regex='^[^[:space:]]+\.[^[:space:]]+$'
-    # Check implicitly deduced name of the source file
-    # for *.* pattern
-    if [[ ${implicitFilename} = 1 ]]; then
-        if [[ ! "${filename}" =~ ${regex} ]]; then
-            msg=$(printf 'filename "%s" not matching *.* pattern' "${filename}")
-            error "${msg}" 3
-        fi
+}
+
+export_args() {
+    export nocompile
+    export compileCmd
+    export norun
+    export runCmd
+    export verbose
+}
+
+prepare_args() {
+    parse_args "$@"
+    parse_input
+    debug_print_args
+    validate_args
+    export_args
+    if [[ ${debug} == 1 ]]; then
+        exit
     fi
 }
 
 main() {
+    prepare_args "$@"
     export -f compileAndRun
-    parse_args "$@"
-    validate
     printf '%s\n' "${monitorFiles[@]}" | \
         entr -rc bash -c compileAndRun
 }
